### ISSUE TITLE
BattleSymphony-1.16b with HolderBattler Issue

### ISSUE THREAD

**Issue by Shad3Light** [suppayami/rmvxa-collection#1]
There is a bug that made Holder Battler users cannot change stance with the current script.

In line 1549, It checks if BattleSymphony-CBS is imported, which I cannot find in your script list, and is not mentioned anywhere in the current Holder add-on as dependency. And in line 1463, it calls the method use_cbs? which is not mentioned anywhere else. Perhaps it is a planned feature?

**Comment by suppayami** [comment]
hello, I have fixed this issue. and yeah, use_cbs? was made for an add-on, which will be released soon.
